
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: "{build}"

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: src/DotLiquid.sln
  publish_nuget: true
  verbosity: minimal

before_build:
  - cmd: nuget restore src/DotLiquid.sln
  - ps: .\tool\scripts\update-build-version.ps1

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: Environment
    name: myget
    on:
      release_tag: true

before_deploy:
  - ps: .\tool\scripts\declare-release-tag.ps1
